#!/bin/sh

mknod /dev/console c 5 1
mknod /dev/ttyAMA0 c 204 64
mknod /dev/ttyAMA1 c 204 65
mknod /dev/ttyAMA2 c 204 66
mknod /dev/ttyS000 c 204 64
mknod /dev/null	   c 1   3
mknod /dev/adc 	   c 95  0

